image: python:3.9-slim-bullseye

stages:
    - tests
#    - deploy


test-job:
  stage: tests
  before_script:
    - pip install -r requirements.txt
  script:
    - pytest --cov=src/main --cov-report=xml --cov-report=term --cov-fail-under=80 src/tests/
  coverage: '/^TOTAL\s+(\d+)%/'
  artifacts:
    paths:
      - coverage.xml
    expire_in: 1 week

codestyle-check:
  stage: tests
  before_script:
    - pip install pycodestyle==2.11.1
  script:
    - pycodestyle src/ --max-line-length 100 || exit 1

#deploy-job:
#  stage: deploy
#  before_script:
#    - apt-get update
#    - apt-get install -y sshpass
#  script:
#    - sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no pi@10.10.1.151 "mkdir -p ~/Team3-Repo"
#    - sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no pi@10.10.1.151 "rm -r ~/Team3-Repo/main"
#    - sshpass -p $SSH_PASSWORD scp -o StrictHostKeyChecking=no -r ./src/main/ pi@10.10.1.151:~/Team3-Repo/
