image: python:3.9-slim-bullseye

stages:
    - build
    - lint
    - tests

build-job:
  stage: build
  script:
    - pip install -r requirements.txt

test-job1:
  stage: tests
  before_script:
    - pip install pytest
  script:
    - pytest src/tests/



