image: python:3.9-slim-bullseye

stages: ## Organize and Order parts of the pipeline
#    - build
    - tests
#    - deploy

#build-job:
#  stage: build
#  script:
#    - pip install -r requirements.txt
#    - echo "Fill Build Stage"

test-job:
  stage: tests
  before_script:
    - pip install -r requirements.txt
  script:
    - pytest --cov=src --cov-report=xml --cov-report=term --cov-fail-under=80 src/tests/
  coverage: '/^TOTAL\s+(\d+)%/'
  artifacts:
    paths:
      - coverage.xml
    expire_in: 1 week

linting:
  stage: tests
  before_script:
    - pip install pylint==3.3.2
  script:
    - find . -type f -name "*.py" | xargs pylint

#deploy-job:
#  stage: deploy
#  only:
#    - main
#  script:
#    - echo "Checking if branch is main..."
#    - if [ "$CI_COMMIT_BRANCH" != "main" ]; then echo "Not on main branch. Skipping deployment."; exit 0; fi
#    - echo "Deploying to Raspberry Pi..."
#    # Replace <RASPBERRY_PI_IP> and <RASPBERRY_PI_USER> with actual values
#    - ssh <RASPBERRY_PI_USER>@<RASPBERRY_PI_IP> '
#        echo "Setting up environment on Raspberry Pi...";
#        # Update package list and ensure Python is installed
#        sudo apt update && sudo apt install -y python3 python3-pip python3-venv;
#        echo "Environment setup complete.";
#      '
#    - echo "Transferring project to Raspberry Pi..."
#    - ssh <RASPBERRY_PI_USER>@<RASPBERRY_PI_IP> 'mkdir -p ~/project'
#    - scp -r ./ <RASPBERRY_PI_USER>@<RASPBERRY_PI_IP>:~/project/
#    - echo "Installing dependencies and running application on Raspberry Pi..."
#    - ssh <RASPBERRY_PI_USER>@<RASPBERRY_PI_IP> '
#        cd ~/project;
#        # Set up virtual environment
#        if [ ! -d "venv" ]; then python3 -m venv venv; fi;
#        source venv/bin/activate;
#        pip install --upgrade pip;
#        pip install -r requirements.txt;
#        echo "Starting application...";
#        python app.py &  # Replace app.py with your entry point;
#        echo "Application started.";
#      '