image: python:3.9-slim-bullseye

stages:
    - build
    - lint
    - tests

build-job:
  stage: build
  script:
    - pip install -r requirements.txt

lint-job:
  stage: lint
  script:
    - flake8 src/main/ src/tests/

test-job1:
  stage: tests
  before_script:
    - pip install pytest
  script:
    - pytest tests/



